Prediction Assignment Writeup
=============================

I used a random forest algorithm to predict in which of the 5 ways a user was performing barbell.


Load Data and clean data (I replace "#DIV/0!" values by "NA"):
```{r}
options(warn=-1)
train_data <- read.csv("pml-training.csv", na.strings=c("#DIV/0!") )
quizz_data <- read.csv("pml-testing.csv", na.strings=c("#DIV/0!") )
train_data <- subset(train_data, select = -c(X, user_name, raw_timestamp_part_1, raw_timestamp_part_2, cvtd_timestamp, new_window, num_window) ) # remove useless columns
quizz_data <- subset(quizz_data, select = -c(X, user_name, raw_timestamp_part_1, raw_timestamp_part_2, cvtd_timestamp, new_window, num_window) ) # remove useless columns
for(i in c(2:ncol(train_data)-1))
{
  train_data[,i] = as.numeric(as.character(train_data[,i]))
} # convert all columns to numeric except the column roll_belt
for(i in c(2:ncol(quizz_data)-1))
{
  quizz_data[,i] = as.numeric(as.character(quizz_data[,i]))
} # convert all columns to numeric except the column roll_belt
train_data$classe <- as.factor(train_data$classe) # transform the variable we try to predict as factor
non_empty_cols <- colnames(train_data[colSums(is.na(train_data)) == 0]) # select empty columns
non_empty_cols
train_data <- train_data[non_empty_cols]
non_empty_cols<-non_empty_cols[non_empty_cols != "classe"]
quizz_data <- quizz_data[non_empty_cols]
```


We split our data set into a training set and a testing set:

```{r}
library(caret)
library(stats)
idx <- createDataPartition(y=train_data$classe, p=0.75, list=FALSE )
train_data <- train_data[idx,]
test_data <- train_data[-idx,]
```


Train model on training data:
```{r}
set.seed(62433)
fitRf <- train(classe ~ ., data=train_data, method="rf")
```


Predict results for the training set and the test set:
```{r}
predRf_train <- predict(fitRf, train_data)
confusionMatrix(predRf_train, train_data)$overall[1]
predRf_test <- predict(fitRf, test_data)
confusionMatrix(predRf_test, test_data)$overall[1]
```

Predict results for the quizz data set:
```{r}
predRf_quizz <- predict(fitRf, quizz_data)
```

